substitutions:
  _PROJECT_ID: "c-01-450604"
  _APP_NAME: "my-next-fe"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$_PROJECT_ID/my-next-fe'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_DATABASE_URL=${_NEXT_PUBLIC_FIREBASE_DATABASE_URL}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_API_SERVER_URL=${_NEXT_PUBLIC_API_SERVER_URL}'
    - '.'
    

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/my-next-fe']


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
    - 'gcloud' 
    - 'app'
    - 'deploy'
    - '--image-url'
    - 'gcr.io/$_PROJECT_ID/my-next-fe'
    - '--promote'
    - '--quiet'


options:
  logging: CLOUD_LOGGING_ONLY
