runtime: nodejs20

env_variables:
  NODE_ENV: 'production'
  NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyDzZyaR5QLTu8gZ6XrUdoTzYRnwHo1Ef50'
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'kelembaban-ruang.firebaseapp.com'
  NEXT_PUBLIC_FIREBASE_DATABASE_URL: 'https://kelembaban-ruang-default-rtdb.firebaseio.com'
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'kelembaban-ruang'
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'kelembaban-ruang.firebasestorage.app'
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '686662801916'
  NEXT_PUBLIC_FIREBASE_APP_ID: '1:686662801916:web:1b1f0e8e23a4b7e44bba79'
  NEXT_PUBLIC_MEASUREMENT_ID: 'G-778L822F4W'
  ADMIN_TYPE: 'service_account'
  ADMIN_PROJECT_ID: 'kelembaban-ruang'
  ADMIN_PRIVATE_KEY_ID: '0a5956597757279878f3980850db23c17b752fa5'
  ADMIN_PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxM99Lfum6SnGf\nd7tIMuvGB2/95afACku9KDxJK8Czb1OjOE8CoUkcaZZ0xGVotu+YLmSRR4RY7tBO\nf2MjwkgsvYAx3zMo2AmDGHGCb5SIJ7mwIv70VRY1eHL024kgs663yZJ0QrMQ+aMv\nnwmsRMsjgacH10JYX+MkD8f9j6i+3aXs/5qXtHCaL2xrBA3qEntyLRzJq8Jz67Up\nOk93Z1orAX4c7RnL6N81LgWZYp1kOiyLkLj2qoSQQRmTPLWJa+2JT3dRtqb31GA0\ne7IlTIm4NO/Uepjy/h8I2zh5bUtAr7ZYeKbiaQLUXB6/xKHq/oiWId4q1TycuBQy\nzGIPODY/AgMBAAECggEALb27FQzUnl7bB5Prhw6F599BnGNssti1hkVdknG101uY\nVliRpJcnfSsQSGHt32LhZAINuaahVieHI8wkNjXPVaUw8y6vUQq7IdjsbAQLbj36\n46mU8FMKYZEO83+73PIk1pI0uMgC2w3lfsRpxcsYOLkd+ZsqKA/QXR2pvR0ZLPMw\ntnL0k3AFpnNoSI21UVBmAy/cJbksWhigipXfuO9m160p6dfFfn/OQBPru2xx4aP5\n/AB8nOhuA5yALpOAP37xXKtqy0dJnTkubi72aODD4e8p7IpIztgMmcV2ijT4ENjF\nyvoQTEciF57YuwNW3BkN/IhH0ZzNemqgl2YAia2BqQKBgQD46vPno4avUwqTSboE\n4GheeL1B9nY/RsqhkEB6CTtOWBLKMjYQJxkV1Pz8jAy8m8Vl3S040jHZ0f43VRwp\nwqkn/l7TtTenpla9pKi1ZW9VYPRijEJoWJqFY+z9/ZLm1dLEktuHRI91psER8gco\nTH+ukFAzW+k6R3hFy3P+vmn6UwKBgQC2PpEAr0Fdm1OJXbq3I6LzUf7WszqQyqk3\nQxtNd0PSsmHDUmTYypQPxl1wBmMJ9TSqHGlVHTy+HMmZJopAKIfFeRJVJyAlrAho\nPB6FUxZo4tnFzqfCDoUFhy3AN24wdFqNJKoaa8EH6Hr6fsbQWmot2VrmgijPmtfM\njp7sJoJO5QKBgAfFXgP3SPckQopCnPoV/2wjnNT4Wsyy6xSMKlck/qL9gOirFKEA\nd3oFAjjoLmWc/1akxwqlFUVVlvgnQg/TsfA7sr4tRCWJvd+BynqPRiCGPFrvQgt7\n6KcNbZKoXfOy7TeR1iSs8UWdBR4ITkzlxn6uprJTxj45iPm01lQ3oZtdAoGAc675\nmoalJodPmrXtrQ0pBe15p83zki+jBJpLfXwEiH2FQ1hM/bRyEiVn8JGNUqfdO1J3\npni9syxQ6C+nuJxBux9kfLsuU9uFJq1q7lTUt9WwSTkqEivnUqABca99+bISPOAW\nPllCGgP/9Hx/NYj/N4Vuhz3+K/Jto8KwrNSxCOUCgYEA73G9QZLRSGrJm4/LEZUk\nMHD6ize+0ZQTcIYTR6vuDxJM6dJsLAKuAT9xP2QqcVC8emw3iQzw0Wl0OEMNz8rM\nvyg8k6iLSfkh8fR26AsmgTKAMthlXXOPlIqJNc4Iakaw25k/JwpcTMCHyaOC1yaO\nFFFetajs8uLrCReIzcUxjD0=\n-----END PRIVATE KEY-----\n'
  ADMIN_CLIENT_EMAIL: 'firebase-adminsdk-ch4sq@kelembaban-ruang.iam.gserviceaccount.com'
  ADMIN_CLIENT_ID: '101268365532429248923'
  ADMIN_AUTH_URI: 'https://accounts.google.com/o/oauth2/auth'
  ADMIN_TOKEN_URI: 'https://oauth2.googleapis.com/token'
  ADMIN_AUTH_PROVIDER_X509_CERT_URL: 'https://www.googleapis.com/oauth2/v1/certs'
  ADMIN_CLIENT_X509_CERT_URL: 'https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ch4sq%40kelembaban-ruang.iam.gserviceaccount.com'
  ADMIN_UNIVERSE_DOMAIN: 'googleapis.com'
  NEXT_PUBLIC_API_SERVER_URL : 'https://my-next-app-948060519163.us-central1.run.app/'

handlers:
  - url: /.*
    script: auto