# Install dependencies and build
FROM node:18-alpine AS builder
WORKDIR /app
COPY . .

# === Define ARGs ===
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_DATABASE_URL
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_MEASUREMENT_ID
ARG ADMIN_TYPE
ARG ADMIN_PROJECT_ID
ARG ADMIN_PRIVATE_KEY_ID
ARG ADMIN_PRIVATE_KEY
ARG ADMIN_CLIENT_EMAIL
ARG ADMIN_CLIENT_ID
ARG ADMIN_AUTH_URI
ARG ADMIN_TOKEN_URI
ARG ADMIN_AUTH_PROVIDER_X509_CERT_URL
ARG ADMIN_CLIENT_X509_CERT_URL
ARG ADMIN_UNIVERSE_DOMAIN
ARG NEXT_PUBLIC_API_SERVER_URL

# === Export as ENV for build-time ===
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY 
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN 
ENV NEXT_PUBLIC_FIREBASE_DATABASE_URL=$NEXT_PUBLIC_FIREBASE_DATABASE_URL 
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID 
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET 
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID 
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID 
ENV NEXT_PUBLIC_MEASUREMENT_ID=$NEXT_PUBLIC_MEASUREMENT_ID 
ENV ADMIN_TYPE=$ADMIN_TYPE 
ENV ADMIN_PROJECT_ID=$ADMIN_PROJECT_ID 
ENV ADMIN_PRIVATE_KEY_ID=$ADMIN_PRIVATE_KEY_ID 
ENV ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY 
ENV ADMIN_CLIENT_EMAIL=$ADMIN_CLIENT_EMAIL 
ENV ADMIN_CLIENT_ID=$ADMIN_CLIENT_ID 
ENV ADMIN_AUTH_URI=$ADMIN_AUTH_URI 
ENV ADMIN_TOKEN_URI=$ADMIN_TOKEN_URI 
ENV ADMIN_AUTH_PROVIDER_X509_CERT_URL=$ADMIN_AUTH_PROVIDER_X509_CERT_URL 
ENV ADMIN_CLIENT_X509_CERT_URL=$ADMIN_CLIENT_X509_CERT_URL 
ENV ADMIN_UNIVERSE_DOMAIN=$ADMIN_UNIVERSE_DOMAIN 
ENV NEXT_PUBLIC_API_SERVER_URL=$NEXT_PUBLIC_API_SERVER_URL

RUN npm ci
RUN npm run build

# Serve with next start
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 8080
ENV PORT 8080
CMD ["npm", "start"]